/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jio.portlet.gallery.model.impl;

import com.jio.portlet.gallery.model.Gallery;
import com.jio.portlet.gallery.service.GalleryLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Gallery service. Represents a row in the &quot;rf_Gallery&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GalleryImpl}.
 * </p>
 *
 * @author Reliance
 * @see GalleryImpl
 * @see com.jio.portlet.gallery.model.Gallery
 * @generated
 */
public abstract class GalleryBaseImpl extends GalleryModelImpl
	implements Gallery {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a gallery model instance should use the {@link Gallery} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			GalleryLocalServiceUtil.addGallery(this);
		}
		else {
			GalleryLocalServiceUtil.updateGallery(this);
		}
	}
}