/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jio.portlet.jurys.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Jurys service. Represents a row in the &quot;GnNext_Jurys&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jio.portlet.jurys.model.impl.JurysModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jio.portlet.jurys.model.impl.JurysImpl}.
 * </p>
 *
 * @author Reliance
 * @see Jurys
 * @see com.jio.portlet.jurys.model.impl.JurysImpl
 * @see com.jio.portlet.jurys.model.impl.JurysModelImpl
 * @generated
 */
public interface JurysModel extends BaseModel<Jurys> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jurys model instance should use the {@link Jurys} interface instead.
	 */

	/**
	 * Returns the primary key of this jurys.
	 *
	 * @return the primary key of this jurys
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this jurys.
	 *
	 * @param primaryKey the primary key of this jurys
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the jurys ID of this jurys.
	 *
	 * @return the jurys ID of this jurys
	 */
	public long getJurysId();

	/**
	 * Sets the jurys ID of this jurys.
	 *
	 * @param jurysId the jurys ID of this jurys
	 */
	public void setJurysId(long jurysId);

	/**
	 * Returns the name of this jurys.
	 *
	 * @return the name of this jurys
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this jurys.
	 *
	 * @param name the name of this jurys
	 */
	public void setName(String name);

	/**
	 * Returns the company name of this jurys.
	 *
	 * @return the company name of this jurys
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this jurys.
	 *
	 * @param companyName the company name of this jurys
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the category of this jurys.
	 *
	 * @return the category of this jurys
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this jurys.
	 *
	 * @param category the category of this jurys
	 */
	public void setCategory(String category);

	/**
	 * Returns the jury image of this jurys.
	 *
	 * @return the jury image of this jurys
	 */
	public Long getJuryImage();

	/**
	 * Sets the jury image of this jurys.
	 *
	 * @param juryImage the jury image of this jurys
	 */
	public void setJuryImage(Long juryImage);

	/**
	 * Returns the short description of this jurys.
	 *
	 * @return the short description of this jurys
	 */
	@AutoEscape
	public String getShortDescription();

	/**
	 * Sets the short description of this jurys.
	 *
	 * @param shortDescription the short description of this jurys
	 */
	public void setShortDescription(String shortDescription);

	/**
	 * Returns the long description of this jurys.
	 *
	 * @return the long description of this jurys
	 */
	@AutoEscape
	public String getLongDescription();

	/**
	 * Sets the long description of this jurys.
	 *
	 * @param longDescription the long description of this jurys
	 */
	public void setLongDescription(String longDescription);

	/**
	 * Returns the number of this jurys.
	 *
	 * @return the number of this jurys
	 */
	public Long getNumber();

	/**
	 * Sets the number of this jurys.
	 *
	 * @param number the number of this jurys
	 */
	public void setNumber(Long number);

	/**
	 * Returns the group ID of this jurys.
	 *
	 * @return the group ID of this jurys
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this jurys.
	 *
	 * @param groupId the group ID of this jurys
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this jurys.
	 *
	 * @return the company ID of this jurys
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this jurys.
	 *
	 * @param companyId the company ID of this jurys
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this jurys.
	 *
	 * @return the create date of this jurys
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this jurys.
	 *
	 * @param createDate the create date of this jurys
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this jurys.
	 *
	 * @return the modified date of this jurys
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this jurys.
	 *
	 * @param modifiedDate the modified date of this jurys
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.jio.portlet.jurys.model.Jurys jurys);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.jio.portlet.jurys.model.Jurys> toCacheModel();

	@Override
	public com.jio.portlet.jurys.model.Jurys toEscapedModel();

	@Override
	public com.jio.portlet.jurys.model.Jurys toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}