create table rf_Gallery (
	galleryId LONG not null primary key,
	type_ VARCHAR(75) null,
	thumbnailName STRING null,
	name STRING null,
	mainCategory VARCHAR(75) null,
	projectImagesPath STRING null,
	galleryImagesId LONG,
	VideoImagesId LONG,
	thumbnailImagesId LONG,
	isVideo BOOLEAN,
	isIMG BOOLEAN,
	youTubeLink BOOLEAN,
	videosImagPriority BOOLEAN,
	gallryImagPriority BOOLEAN,
	demoLink VARCHAR(75) null,
	liveLink VARCHAR(75) null,
	number_ LONG,
	createDate DATE null,
	modifiedDate DATE null
);