create table gns_Startups (
	startupsId LONG not null primary key,
	name VARCHAR(75) null,
	companyName VARCHAR(75) null,
	category VARCHAR(75) null,
	startupImage LONG,
	youtubeImages LONG,
	youtubeLink VARCHAR(75) null,
	shortDescription STRING null,
	startupDesc STRING null,
	longDescription STRING null,
	twitter VARCHAR(75) null,
	linkedIn VARCHAR(75) null,
	youTube VARCHAR(75) null,
	number_ LONG,
	groupId LONG,
	companyId LONG,
	createDate DATE null,
	modifiedDate DATE null
);