/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jio.portlet.jurys.model.impl;

import com.jio.portlet.jurys.model.Jurys;
import com.jio.portlet.jurys.model.JurysModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Jurys service. Represents a row in the &quot;GnNext_Jurys&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.jio.portlet.jurys.model.JurysModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JurysImpl}.
 * </p>
 *
 * @author Reliance
 * @see JurysImpl
 * @see com.jio.portlet.jurys.model.Jurys
 * @see com.jio.portlet.jurys.model.JurysModel
 * @generated
 */
public class JurysModelImpl extends BaseModelImpl<Jurys> implements JurysModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a jurys model instance should use the {@link com.jio.portlet.jurys.model.Jurys} interface instead.
	 */
	public static final String TABLE_NAME = "GnNext_Jurys";
	public static final Object[][] TABLE_COLUMNS = {
			{ "jurysId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "companyName", Types.VARCHAR },
			{ "category", Types.VARCHAR },
			{ "juryImage", Types.BIGINT },
			{ "shortDescription", Types.VARCHAR },
			{ "longDescription", Types.VARCHAR },
			{ "number_", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table GnNext_Jurys (jurysId LONG not null primary key,name VARCHAR(75) null,companyName VARCHAR(75) null,category VARCHAR(75) null,juryImage LONG,shortDescription STRING null,longDescription STRING null,number_ LONG,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table GnNext_Jurys";
	public static final String ORDER_BY_JPQL = " ORDER BY jurys.jurysId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GnNext_Jurys.jurysId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.jio.portlet.jurys.model.Jurys"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.jio.portlet.jurys.model.Jurys"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.jio.portlet.jurys.model.Jurys"));

	public JurysModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _jurysId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setJurysId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _jurysId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Jurys.class;
	}

	@Override
	public String getModelClassName() {
		return Jurys.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("jurysId", getJurysId());
		attributes.put("name", getName());
		attributes.put("companyName", getCompanyName());
		attributes.put("category", getCategory());
		attributes.put("juryImage", getJuryImage());
		attributes.put("shortDescription", getShortDescription());
		attributes.put("longDescription", getLongDescription());
		attributes.put("number", getNumber());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long jurysId = (Long)attributes.get("jurysId");

		if (jurysId != null) {
			setJurysId(jurysId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String companyName = (String)attributes.get("companyName");

		if (companyName != null) {
			setCompanyName(companyName);
		}

		String category = (String)attributes.get("category");

		if (category != null) {
			setCategory(category);
		}

		Long juryImage = (Long)attributes.get("juryImage");

		if (juryImage != null) {
			setJuryImage(juryImage);
		}

		String shortDescription = (String)attributes.get("shortDescription");

		if (shortDescription != null) {
			setShortDescription(shortDescription);
		}

		String longDescription = (String)attributes.get("longDescription");

		if (longDescription != null) {
			setLongDescription(longDescription);
		}

		Long number = (Long)attributes.get("number");

		if (number != null) {
			setNumber(number);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@Override
	public long getJurysId() {
		return _jurysId;
	}

	@Override
	public void setJurysId(long jurysId) {
		_jurysId = jurysId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getCompanyName() {
		if (_companyName == null) {
			return StringPool.BLANK;
		}
		else {
			return _companyName;
		}
	}

	@Override
	public void setCompanyName(String companyName) {
		_companyName = companyName;
	}

	@Override
	public String getCategory() {
		if (_category == null) {
			return StringPool.BLANK;
		}
		else {
			return _category;
		}
	}

	@Override
	public void setCategory(String category) {
		_category = category;
	}

	@Override
	public Long getJuryImage() {
		return _juryImage;
	}

	@Override
	public void setJuryImage(Long juryImage) {
		_juryImage = juryImage;
	}

	@Override
	public String getShortDescription() {
		if (_shortDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _shortDescription;
		}
	}

	@Override
	public void setShortDescription(String shortDescription) {
		_shortDescription = shortDescription;
	}

	@Override
	public String getLongDescription() {
		if (_longDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _longDescription;
		}
	}

	@Override
	public void setLongDescription(String longDescription) {
		_longDescription = longDescription;
	}

	@Override
	public Long getNumber() {
		return _number;
	}

	@Override
	public void setNumber(Long number) {
		_number = number;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Jurys.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Jurys toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Jurys)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		JurysImpl jurysImpl = new JurysImpl();

		jurysImpl.setJurysId(getJurysId());
		jurysImpl.setName(getName());
		jurysImpl.setCompanyName(getCompanyName());
		jurysImpl.setCategory(getCategory());
		jurysImpl.setJuryImage(getJuryImage());
		jurysImpl.setShortDescription(getShortDescription());
		jurysImpl.setLongDescription(getLongDescription());
		jurysImpl.setNumber(getNumber());
		jurysImpl.setGroupId(getGroupId());
		jurysImpl.setCompanyId(getCompanyId());
		jurysImpl.setCreateDate(getCreateDate());
		jurysImpl.setModifiedDate(getModifiedDate());

		jurysImpl.resetOriginalValues();

		return jurysImpl;
	}

	@Override
	public int compareTo(Jurys jurys) {
		long primaryKey = jurys.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Jurys)) {
			return false;
		}

		Jurys jurys = (Jurys)obj;

		long primaryKey = jurys.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Jurys> toCacheModel() {
		JurysCacheModel jurysCacheModel = new JurysCacheModel();

		jurysCacheModel.jurysId = getJurysId();

		jurysCacheModel.name = getName();

		String name = jurysCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			jurysCacheModel.name = null;
		}

		jurysCacheModel.companyName = getCompanyName();

		String companyName = jurysCacheModel.companyName;

		if ((companyName != null) && (companyName.length() == 0)) {
			jurysCacheModel.companyName = null;
		}

		jurysCacheModel.category = getCategory();

		String category = jurysCacheModel.category;

		if ((category != null) && (category.length() == 0)) {
			jurysCacheModel.category = null;
		}

		jurysCacheModel.juryImage = getJuryImage();

		jurysCacheModel.shortDescription = getShortDescription();

		String shortDescription = jurysCacheModel.shortDescription;

		if ((shortDescription != null) && (shortDescription.length() == 0)) {
			jurysCacheModel.shortDescription = null;
		}

		jurysCacheModel.longDescription = getLongDescription();

		String longDescription = jurysCacheModel.longDescription;

		if ((longDescription != null) && (longDescription.length() == 0)) {
			jurysCacheModel.longDescription = null;
		}

		jurysCacheModel.number = getNumber();

		jurysCacheModel.groupId = getGroupId();

		jurysCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			jurysCacheModel.createDate = createDate.getTime();
		}
		else {
			jurysCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			jurysCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			jurysCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return jurysCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{jurysId=");
		sb.append(getJurysId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", companyName=");
		sb.append(getCompanyName());
		sb.append(", category=");
		sb.append(getCategory());
		sb.append(", juryImage=");
		sb.append(getJuryImage());
		sb.append(", shortDescription=");
		sb.append(getShortDescription());
		sb.append(", longDescription=");
		sb.append(getLongDescription());
		sb.append(", number=");
		sb.append(getNumber());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.jio.portlet.jurys.model.Jurys");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>jurysId</column-name><column-value><![CDATA[");
		sb.append(getJurysId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyName</column-name><column-value><![CDATA[");
		sb.append(getCompanyName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>category</column-name><column-value><![CDATA[");
		sb.append(getCategory());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>juryImage</column-name><column-value><![CDATA[");
		sb.append(getJuryImage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shortDescription</column-name><column-value><![CDATA[");
		sb.append(getShortDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>longDescription</column-name><column-value><![CDATA[");
		sb.append(getLongDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>number</column-name><column-value><![CDATA[");
		sb.append(getNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Jurys.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Jurys.class };
	private long _jurysId;
	private String _name;
	private String _companyName;
	private String _category;
	private Long _juryImage;
	private String _shortDescription;
	private String _longDescription;
	private Long _number;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private Jurys _escapedModel;
}