/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jio.portlet.mentors.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Mentors service. Represents a row in the &quot;gn_Mentors&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jio.portlet.mentors.model.impl.MentorsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jio.portlet.mentors.model.impl.MentorsImpl}.
 * </p>
 *
 * @author Reliance
 * @see Mentors
 * @see com.jio.portlet.mentors.model.impl.MentorsImpl
 * @see com.jio.portlet.mentors.model.impl.MentorsModelImpl
 * @generated
 */
public interface MentorsModel extends BaseModel<Mentors> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mentors model instance should use the {@link Mentors} interface instead.
	 */

	/**
	 * Returns the primary key of this mentors.
	 *
	 * @return the primary key of this mentors
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mentors.
	 *
	 * @param primaryKey the primary key of this mentors
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mentors ID of this mentors.
	 *
	 * @return the mentors ID of this mentors
	 */
	public long getMentorsId();

	/**
	 * Sets the mentors ID of this mentors.
	 *
	 * @param mentorsId the mentors ID of this mentors
	 */
	public void setMentorsId(long mentorsId);

	/**
	 * Returns the name of this mentors.
	 *
	 * @return the name of this mentors
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this mentors.
	 *
	 * @param name the name of this mentors
	 */
	public void setName(String name);

	/**
	 * Returns the company name of this mentors.
	 *
	 * @return the company name of this mentors
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this mentors.
	 *
	 * @param companyName the company name of this mentors
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the category of this mentors.
	 *
	 * @return the category of this mentors
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this mentors.
	 *
	 * @param category the category of this mentors
	 */
	public void setCategory(String category);

	/**
	 * Returns the mentor image of this mentors.
	 *
	 * @return the mentor image of this mentors
	 */
	public Long getMentorImage();

	/**
	 * Sets the mentor image of this mentors.
	 *
	 * @param mentorImage the mentor image of this mentors
	 */
	public void setMentorImage(Long mentorImage);

	/**
	 * Returns the short description of this mentors.
	 *
	 * @return the short description of this mentors
	 */
	@AutoEscape
	public String getShortDescription();

	/**
	 * Sets the short description of this mentors.
	 *
	 * @param shortDescription the short description of this mentors
	 */
	public void setShortDescription(String shortDescription);

	/**
	 * Returns the long description of this mentors.
	 *
	 * @return the long description of this mentors
	 */
	@AutoEscape
	public String getLongDescription();

	/**
	 * Sets the long description of this mentors.
	 *
	 * @param longDescription the long description of this mentors
	 */
	public void setLongDescription(String longDescription);

	/**
	 * Returns the number of this mentors.
	 *
	 * @return the number of this mentors
	 */
	public Long getNumber();

	/**
	 * Sets the number of this mentors.
	 *
	 * @param number the number of this mentors
	 */
	public void setNumber(Long number);

	/**
	 * Returns the group ID of this mentors.
	 *
	 * @return the group ID of this mentors
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this mentors.
	 *
	 * @param groupId the group ID of this mentors
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this mentors.
	 *
	 * @return the company ID of this mentors
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this mentors.
	 *
	 * @param companyId the company ID of this mentors
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this mentors.
	 *
	 * @return the create date of this mentors
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this mentors.
	 *
	 * @param createDate the create date of this mentors
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this mentors.
	 *
	 * @return the modified date of this mentors
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mentors.
	 *
	 * @param modifiedDate the modified date of this mentors
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.jio.portlet.mentors.model.Mentors mentors);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.jio.portlet.mentors.model.Mentors> toCacheModel();

	@Override
	public com.jio.portlet.mentors.model.Mentors toEscapedModel();

	@Override
	public com.jio.portlet.mentors.model.Mentors toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}