/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jio.portlet.startups.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Startups service. Represents a row in the &quot;gns_Startups&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jio.portlet.startups.model.impl.StartupsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jio.portlet.startups.model.impl.StartupsImpl}.
 * </p>
 *
 * @author rajnikant.donga
 * @see Startups
 * @see com.jio.portlet.startups.model.impl.StartupsImpl
 * @see com.jio.portlet.startups.model.impl.StartupsModelImpl
 * @generated
 */
public interface StartupsModel extends BaseModel<Startups> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a startups model instance should use the {@link Startups} interface instead.
	 */

	/**
	 * Returns the primary key of this startups.
	 *
	 * @return the primary key of this startups
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this startups.
	 *
	 * @param primaryKey the primary key of this startups
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the startups ID of this startups.
	 *
	 * @return the startups ID of this startups
	 */
	public long getStartupsId();

	/**
	 * Sets the startups ID of this startups.
	 *
	 * @param startupsId the startups ID of this startups
	 */
	public void setStartupsId(long startupsId);

	/**
	 * Returns the name of this startups.
	 *
	 * @return the name of this startups
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this startups.
	 *
	 * @param name the name of this startups
	 */
	public void setName(String name);

	/**
	 * Returns the company name of this startups.
	 *
	 * @return the company name of this startups
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this startups.
	 *
	 * @param companyName the company name of this startups
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the category of this startups.
	 *
	 * @return the category of this startups
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this startups.
	 *
	 * @param category the category of this startups
	 */
	public void setCategory(String category);

	/**
	 * Returns the startup image of this startups.
	 *
	 * @return the startup image of this startups
	 */
	public Long getStartupImage();

	/**
	 * Sets the startup image of this startups.
	 *
	 * @param startupImage the startup image of this startups
	 */
	public void setStartupImage(Long startupImage);

	/**
	 * Returns the youtube images of this startups.
	 *
	 * @return the youtube images of this startups
	 */
	public Long getYoutubeImages();

	/**
	 * Sets the youtube images of this startups.
	 *
	 * @param youtubeImages the youtube images of this startups
	 */
	public void setYoutubeImages(Long youtubeImages);

	/**
	 * Returns the youtube link of this startups.
	 *
	 * @return the youtube link of this startups
	 */
	@AutoEscape
	public String getYoutubeLink();

	/**
	 * Sets the youtube link of this startups.
	 *
	 * @param youtubeLink the youtube link of this startups
	 */
	public void setYoutubeLink(String youtubeLink);

	/**
	 * Returns the short description of this startups.
	 *
	 * @return the short description of this startups
	 */
	@AutoEscape
	public String getShortDescription();

	/**
	 * Sets the short description of this startups.
	 *
	 * @param shortDescription the short description of this startups
	 */
	public void setShortDescription(String shortDescription);

	/**
	 * Returns the startup desc of this startups.
	 *
	 * @return the startup desc of this startups
	 */
	@AutoEscape
	public String getStartupDesc();

	/**
	 * Sets the startup desc of this startups.
	 *
	 * @param startupDesc the startup desc of this startups
	 */
	public void setStartupDesc(String startupDesc);

	/**
	 * Returns the long description of this startups.
	 *
	 * @return the long description of this startups
	 */
	@AutoEscape
	public String getLongDescription();

	/**
	 * Sets the long description of this startups.
	 *
	 * @param longDescription the long description of this startups
	 */
	public void setLongDescription(String longDescription);

	/**
	 * Returns the twitter of this startups.
	 *
	 * @return the twitter of this startups
	 */
	@AutoEscape
	public String getTwitter();

	/**
	 * Sets the twitter of this startups.
	 *
	 * @param twitter the twitter of this startups
	 */
	public void setTwitter(String twitter);

	/**
	 * Returns the linked in of this startups.
	 *
	 * @return the linked in of this startups
	 */
	@AutoEscape
	public String getLinkedIn();

	/**
	 * Sets the linked in of this startups.
	 *
	 * @param linkedIn the linked in of this startups
	 */
	public void setLinkedIn(String linkedIn);

	/**
	 * Returns the you tube of this startups.
	 *
	 * @return the you tube of this startups
	 */
	@AutoEscape
	public String getYouTube();

	/**
	 * Sets the you tube of this startups.
	 *
	 * @param youTube the you tube of this startups
	 */
	public void setYouTube(String youTube);

	/**
	 * Returns the number of this startups.
	 *
	 * @return the number of this startups
	 */
	public Long getNumber();

	/**
	 * Sets the number of this startups.
	 *
	 * @param number the number of this startups
	 */
	public void setNumber(Long number);

	/**
	 * Returns the group ID of this startups.
	 *
	 * @return the group ID of this startups
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this startups.
	 *
	 * @param groupId the group ID of this startups
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this startups.
	 *
	 * @return the company ID of this startups
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this startups.
	 *
	 * @param companyId the company ID of this startups
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this startups.
	 *
	 * @return the create date of this startups
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this startups.
	 *
	 * @param createDate the create date of this startups
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this startups.
	 *
	 * @return the modified date of this startups
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this startups.
	 *
	 * @param modifiedDate the modified date of this startups
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.jio.portlet.startups.model.Startups startups);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.jio.portlet.startups.model.Startups> toCacheModel();

	@Override
	public com.jio.portlet.startups.model.Startups toEscapedModel();

	@Override
	public com.jio.portlet.startups.model.Startups toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}