/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jio.portlet.mentors.model.impl;

import com.jio.portlet.mentors.model.Mentors;
import com.jio.portlet.mentors.service.MentorsLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Mentors service. Represents a row in the &quot;gn_Mentors&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MentorsImpl}.
 * </p>
 *
 * @author Reliance
 * @see MentorsImpl
 * @see com.jio.portlet.mentors.model.Mentors
 * @generated
 */
public abstract class MentorsBaseImpl extends MentorsModelImpl
	implements Mentors {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mentors model instance should use the {@link Mentors} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			MentorsLocalServiceUtil.addMentors(this);
		}
		else {
			MentorsLocalServiceUtil.updateMentors(this);
		}
	}
}